apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ryanj3-poi-map-app-dev
  annotations:
    argocd/app-name: ryanj3-poi-map-app-dev
    backstage.io/kubernetes-id: ryanj3-poi-map-app-dev
    backstage.io/kubernetes-namespace: ryanj3
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/ryanj3-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/ryanj3/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/ryanj3/deployments/ryanj3-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/ryanj3-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://ryanj3-poi-map-app-ryanj3.apps.rosa916.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-ryanj3
  consumesApis:
    - gateway-api-ryanj3
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ryanj3
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
